//! Strategies generated by the natural-language pipeline (lab "전략 생성").
//!
//! This file is REGENERATED WHOLESALE by each generation run — hand edits
//! are lost. Every strategy here passed the compile gate, and is marked
//! "미검증(생성)" in the registry: it was machine-written and has not had
//! human review.

use crate::strategy::Strategy;
use crate::strategy_registry::StrategySpec;
use crate::types::{Quantity, Symbol};

pub fn specs() -> Vec<StrategySpec> {
    Vec::new()
}

pub fn build(_key: &str, _symbols: &[Symbol], _quantity: Quantity) -> Option<Box<dyn Strategy>> {
    None
}
